const MusicData = [
  {
    id: 0,
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    year: 2017,
    cover_image: "./covers/1.jpg",
    music_path: "./songs/1.mp3",
  },
  {
    id: 1,
    title: "Let Me Down Slowly",
    artist: "Alec Benjamin",
    genre: "Pop",
    year: 2018,
    cover_image: "./covers/2.jpg",
    music_path: "./songs/2.mp3",
  },
  {
    id: 2,
    title: "On My Way",
    artist: "Alan Walker, Sabrina Carpenter & Farruko",
    genre: "Electronic",
    year: 2019,
    cover_image: "./covers/3.jpg",
    music_path: "./songs/3.mp3",
  },
  {
    id: 3,
    title: "Night Changes",
    artist: "One Direction",
    genre: "Pop",
    year: 2014,
    cover_image: "./covers/4.jpg",
    music_path: "./songs/4.mp3",
  },
  {
    id: 4,
    title: "Closer",
    artist: "The Chainsmokers ft. Halsey",
    genre: "Electronic",
    year: 2016,
    cover_image: "./covers/5.jpg",
    music_path: "./songs/5.mp3",
  },
  {
    id: 5,
    title: "Stay",
    artist: "Post Malone",
    genre: "Pop",
    year: 2018,
    cover_image: "./covers/6.jpg",
    music_path: "./songs/6.mp3",
  },
  {
    id: 6,
    title: "Calm Down",
    artist: "Taylor Swift",
    genre: "Pop",
    year: 2019,
    cover_image: "./covers/7.jpg",
    music_path: "./songs/7.mp3",
  },
  {
    id: 7,
    title: "Dandelions",
    artist: "Ruth B.",
    genre: "Pop",
    year: 2020,
    cover_image: "./covers/8.jpg",
    music_path: "./songs/8.mp3",
  },
  {
    id: 8,
    title: "Arcade",
    artist: "Duncan Laurence",
    genre: "Pop",
    year: 2019,
    cover_image: "./covers/9.jpg",
    music_path: "./songs/9.mp3",
  },
  {
    id: 9,
    title: "Tokyo Drift (Fast & Furious)",
    artist: "Teriyaki Boyz",
    genre: "Hip Hop",
    year: 2006,
    cover_image: "./covers/10.jpg",
    music_path: "./songs/10.mp3",
  },
];

localStorage.setItem("MusicData", JSON.stringify(MusicData));
